//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.CalculadoraService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculadoraService.ICalculadoraService")]
    public interface ICalculadoraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadoraService/Sumar", ReplyAction="http://tempuri.org/ICalculadoraService/SumarResponse")]
        double Sumar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadoraService/Sumar", ReplyAction="http://tempuri.org/ICalculadoraService/SumarResponse")]
        System.Threading.Tasks.Task<double> SumarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadoraService/Restar", ReplyAction="http://tempuri.org/ICalculadoraService/RestarResponse")]
        double Restar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadoraService/Restar", ReplyAction="http://tempuri.org/ICalculadoraService/RestarResponse")]
        System.Threading.Tasks.Task<double> RestarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadoraService/Multiplicar", ReplyAction="http://tempuri.org/ICalculadoraService/MultiplicarResponse")]
        double Multiplicar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadoraService/Multiplicar", ReplyAction="http://tempuri.org/ICalculadoraService/MultiplicarResponse")]
        System.Threading.Tasks.Task<double> MultiplicarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadoraService/Dividir", ReplyAction="http://tempuri.org/ICalculadoraService/DividirResponse")]
        double Dividir(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadoraService/Dividir", ReplyAction="http://tempuri.org/ICalculadoraService/DividirResponse")]
        System.Threading.Tasks.Task<double> DividirAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculadoraServiceChannel : ServiceClient.CalculadoraService.ICalculadoraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraServiceClient : System.ServiceModel.ClientBase<ServiceClient.CalculadoraService.ICalculadoraService>, ServiceClient.CalculadoraService.ICalculadoraService {
        
        public CalculadoraServiceClient() {
        }
        
        public CalculadoraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Sumar(double a, double b) {
            return base.Channel.Sumar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SumarAsync(double a, double b) {
            return base.Channel.SumarAsync(a, b);
        }
        
        public double Restar(double a, double b) {
            return base.Channel.Restar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> RestarAsync(double a, double b) {
            return base.Channel.RestarAsync(a, b);
        }
        
        public double Multiplicar(double a, double b) {
            return base.Channel.Multiplicar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> MultiplicarAsync(double a, double b) {
            return base.Channel.MultiplicarAsync(a, b);
        }
        
        public double Dividir(double a, double b) {
            return base.Channel.Dividir(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DividirAsync(double a, double b) {
            return base.Channel.DividirAsync(a, b);
        }
    }
}
